# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('overview', models.CharField(max_length=2000)),
                ('rating', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='search_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('movie_id', models.IntegerField(max_length=200)),
            ],
        ),
    ]
