# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='search_movie',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='search_movie',
            name='movie_title',
        ),
        migrations.RemoveField(
            model_name='search_movie',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='search_movie',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='search_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.search_movie'),
        ),
    ]
