# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0002_auto_20170604_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='search_movie',
            name='movie_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
