# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0003_search_movie_movie_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_overview',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
