# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0004_movie_movie_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_id',
            name='language',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie_id',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie_id',
            name='rating',
            field=models.FloatField(max_length=20),
        ),
    ]
