# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0005_auto_20170605_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_character', models.CharField(max_length=200)),
                ('movie_actor', models.CharField(max_length=200)),
                ('actor_id', models.IntegerField(default=0)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie_id')),
            ],
        ),
    ]
