# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_character', models.CharField(max_length=200)),
                ('movie_actor', models.CharField(max_length=200)),
                ('actor_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('movie_id', models.IntegerField()),
                ('movie_overview', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='movie_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('overview', models.CharField(max_length=2000)),
                ('rating', models.FloatField(max_length=20)),
                ('movie_id', models.IntegerField(default=0)),
                ('language', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=2000)),
                ('movie_review', models.CharField(default='None', max_length=2000)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie_id')),
            ],
        ),
        migrations.CreateModel(
            name='search_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('movie_text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='search_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.search_movie'),
        ),
        migrations.AddField(
            model_name='character',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdb.movie_id'),
        ),
    ]
