# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0004_now_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='now_playing',
            name='poster_path',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
