# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0006_auto_20170608_2119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Now_playing',
            new_name='Playing',
        ),
    ]
