# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0007_auto_20170608_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Known',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known', models.CharField(default='', max_length=200)),
                ('People_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tmdb.People_detail')),
            ],
        ),
    ]
