# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0008_known'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people_detail',
            name='people_id',
        ),
    ]
