# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0009_remove_people_detail_people_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='known',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
