# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0011_auto_20170608_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='known1',
            name='character',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
