# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0012_auto_20170608_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_id',
            name='image',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
