# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0013_movie_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_detail',
            name='image',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
