# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0016_auto_20170609_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='playing',
            name='trailer',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
