# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0017_playing_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_id',
            name='trailer',
            field=models.SlugField(blank=True, default='', max_length=200, null=True),
        ),
    ]
