# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdb', '0018_movie_id_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='known1',
            name='release_date',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='date published'),
        ),
    ]
